[project]
name = "cl677"
version = "0.1.0"
description = "Modelling Stochastic and Turbulent Transport - CL677"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.19.4",
    "numpy>=1.24.0",
    "matplotlib>=3.7.0",
    "scipy>=1.17.0",
    "google-genai>=1.62.0",
    "pydantic-ai-slim>=1.55.0",
    "nbconvert>=7.17.0",
    "nbformat>=5.10.4",
    "playwright>=1.58.0",
]
